contributionGuidelines:
  title: How to Contribute
  content: >
    Thank you for your interest in contributing to this project! This project is primarily a learning resource, and as such, we do not merge pull requests. However, we encourage you to create an issue if you have suggestions on how we can improve the project. Your input is valuable to us, and we appreciate your contributions.