name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Upgrades"
    semver-increment: "major"
    labels:
      - "breaking"
      - "major"

  - title: "Features"
    semver-increment: "major"
    labels:
      - "feat"
      - "minor"

  - title: "Improvements"
    semver-increment: "patch"
    labels:
      - "fix"
      - "perf"
      - "test"
      - "chore"
      - "patch"

  - type: "pre-exclude"
    when:
      label: "skip-changelog"

template: |
  <Accordions>
    $CHANGES
  </Accordions>

category-template: |
  <Accordion title="$TITLE">
    $ENTRIES
  </Accordion>

change-template: "- $TITLE ([#$NUMBER]($URL)) by @$AUTHOR"
