services:
  portman_database:
    image: postgres:18-alpine
    container_name: portman_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portman
    networks: 
      - portman_network
    volumes:
      - portman_volume:/var/lib/postgresql
    ports:
      - "5432:5432"

  portman_cache:
    image: redis:8-alpine
    container_name: portman_cache
    restart: unless-stopped
    networks: 
      - portman_network
    ports:
      - "6379:6379"

  portman_queue:
    image: nats:2-alpine
    container_name: portman_queue
    restart: unless-stopped
    networks: 
      - portman_network
    ports:
      - "4222:4222"

networks:
  portman_network:
    name: portman_network

volumes:
  portman_volume:
    name: portman_volume
