set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

run amount="10":
    @echo "Starting Portman Bots"
    uv run main.py --amount={{ amount }}

test:
    @echo "Running tests"
    uv run pytest
