// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package repositories

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (name, symbol, decimals, kind)
VALUES ($1, $2, $3, $4)
RETURNING id, name, symbol, decimals, kind, created_at, updated_at, deleted_at
`

type CreateAssetParams struct {
	Name     string    `json:"name"`
	Symbol   string    `json:"symbol"`
	Decimals int32     `json:"decimals"`
	Kind     AssetKind `json:"kind"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.Kind,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
UPDATE assets
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const findAssetBySymbol = `-- name: FindAssetBySymbol :one
SELECT id, name, symbol, decimals, kind, created_at, updated_at, deleted_at FROM assets
WHERE symbol = $1 LIMIT 1
`

func (q *Queries) FindAssetBySymbol(ctx context.Context, symbol string) (Asset, error) {
	row := q.db.QueryRow(ctx, findAssetBySymbol, symbol)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, name, symbol, decimals, kind, created_at, updated_at, deleted_at FROM assets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id int32) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, symbol, decimals, kind, created_at, updated_at, deleted_at FROM assets
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
