// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balances.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createBalance = `-- name: CreateBalance :one
INSERT INTO balances (user_id, asset_id, available, locked)
VALUES ($1, $2, $3, $4)
RETURNING user_id, asset_id, available, locked
`

type CreateBalanceParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	AssetID   int32           `json:"asset_id"`
	Available decimal.Decimal `json:"available"`
	Locked    decimal.Decimal `json:"locked"`
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, createBalance,
		arg.UserID,
		arg.AssetID,
		arg.Available,
		arg.Locked,
	)
	var i Balance
	err := row.Scan(
		&i.UserID,
		&i.AssetID,
		&i.Available,
		&i.Locked,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT user_id, asset_id, available, locked FROM balances
WHERE user_id = $1 AND asset_id = $2 LIMIT 1
`

type GetBalanceParams struct {
	UserID  uuid.UUID `json:"user_id"`
	AssetID int32     `json:"asset_id"`
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.UserID, arg.AssetID)
	var i Balance
	err := row.Scan(
		&i.UserID,
		&i.AssetID,
		&i.Available,
		&i.Locked,
	)
	return i, err
}

const listBalances = `-- name: ListBalances :many
SELECT user_id, asset_id, available, locked FROM balances
WHERE user_id = $1
ORDER BY asset_id
`

func (q *Queries) ListBalances(ctx context.Context, userID uuid.UUID) ([]Balance, error) {
	rows, err := q.db.Query(ctx, listBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.UserID,
			&i.AssetID,
			&i.Available,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE balances
SET available = $3, locked = $4
WHERE user_id = $1 AND asset_id = $2
`

type UpdateBalanceParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	AssetID   int32           `json:"asset_id"`
	Available decimal.Decimal `json:"available"`
	Locked    decimal.Decimal `json:"locked"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance,
		arg.UserID,
		arg.AssetID,
		arg.Available,
		arg.Locked,
	)
	return err
}
