// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AssetKind string

const (
	AssetKindCRYPTO    AssetKind = "CRYPTO"
	AssetKindSTOCK     AssetKind = "STOCK"
	AssetKindFIAT      AssetKind = "FIAT"
	AssetKindCOMMODITY AssetKind = "COMMODITY"
)

func (e *AssetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetKind(s)
	case string:
		*e = AssetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetKind: %T", src)
	}
	return nil
}

type NullAssetKind struct {
	AssetKind AssetKind `json:"asset_kind"`
	Valid     bool      `json:"valid"` // Valid is true if AssetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetKind) Scan(value interface{}) error {
	if value == nil {
		ns.AssetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetKind), nil
}

type OrderMode string

const (
	OrderModeGTC OrderMode = "GTC"
	OrderModeFOK OrderMode = "FOK"
	OrderModeIOC OrderMode = "IOC"
)

func (e *OrderMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderMode(s)
	case string:
		*e = OrderMode(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderMode: %T", src)
	}
	return nil
}

type NullOrderMode struct {
	OrderMode OrderMode `json:"order_mode"`
	Valid     bool      `json:"valid"` // Valid is true if OrderMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderMode) Scan(value interface{}) error {
	if value == nil {
		ns.OrderMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderMode), nil
}

type OrderSide string

const (
	OrderSideBUY  OrderSide = "BUY"
	OrderSideSELL OrderSide = "SELL"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide `json:"order_side"`
	Valid     bool      `json:"valid"` // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

type OrderStatus string

const (
	OrderStatusPENDING   OrderStatus = "PENDING"
	OrderStatusREJECTED  OrderStatus = "REJECTED"
	OrderStatusPARTIAL   OrderStatus = "PARTIAL"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
	OrderStatusFULFILLED OrderStatus = "FULFILLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type TickerStatus string

const (
	TickerStatusOPEN      TickerStatus = "OPEN"
	TickerStatusCLOSED    TickerStatus = "CLOSED"
	TickerStatusSUSPENDED TickerStatus = "SUSPENDED"
)

func (e *TickerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TickerStatus(s)
	case string:
		*e = TickerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TickerStatus: %T", src)
	}
	return nil
}

type NullTickerStatus struct {
	TickerStatus TickerStatus `json:"ticker_status"`
	Valid        bool         `json:"valid"` // Valid is true if TickerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTickerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TickerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TickerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTickerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TickerStatus), nil
}

type UserRole string

const (
	UserRoleREGULAR       UserRole = "REGULAR"
	UserRoleAUTOMATED     UserRole = "AUTOMATED"
	UserRoleADMINISTRATOR UserRole = "ADMINISTRATOR"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Asset struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Symbol    string             `json:"symbol"`
	Decimals  int32              `json:"decimals"`
	Kind      AssetKind          `json:"kind"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Balance struct {
	UserID    uuid.UUID       `json:"user_id"`
	AssetID   int32           `json:"asset_id"`
	Available decimal.Decimal `json:"available"`
	Locked    decimal.Decimal `json:"locked"`
}

type Order struct {
	ID        int64           `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	TickerID  int64           `json:"ticker_id"`
	Price     decimal.Decimal `json:"price"`
	Quantity  decimal.Decimal `json:"quantity"`
	Side      OrderSide       `json:"side"`
	Mode      OrderMode       `json:"mode"`
	Status    OrderStatus     `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Ticker struct {
	ID         int64              `json:"id"`
	Symbol     string             `json:"symbol"`
	LotSize    decimal.Decimal    `json:"lot_size"`
	TickSize   decimal.Decimal    `json:"tick_size"`
	Ask        decimal.Decimal    `json:"ask"`
	Bid        decimal.Decimal    `json:"bid"`
	BaseAsset  int32              `json:"base_asset"`
	QuoteAsset int32              `json:"quote_asset"`
	Status     TickerStatus       `json:"status"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	EmailAddress  string             `json:"email_address"`
	WalletAddress string             `json:"wallet_address"`
	Password      string             `json:"password"`
	ApiKey        *string            `json:"api_key"`
	Role          UserRole           `json:"role"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
