// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ticker struct {
	ID     int32         `json:"id"`
	Symbol string        `json:"symbol"`
	Name   string        `json:"name"`
	Last   pgtype.Float4 `json:"last"`
	Ask    pgtype.Float4 `json:"ask"`
	Bid    pgtype.Float4 `json:"bid"`
}
