// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, ticker_id, price, quantity, order_side, order_mode)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, ticker_id, price, quantity, order_side, order_mode, order_status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	TickerID  int64           `json:"ticker_id"`
	Price     decimal.Decimal `json:"price"`
	Quantity  decimal.Decimal `json:"quantity"`
	OrderSide OrderSide       `json:"order_side"`
	OrderMode OrderMode       `json:"order_mode"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.TickerID,
		arg.Price,
		arg.Quantity,
		arg.OrderSide,
		arg.OrderMode,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TickerID,
		&i.Price,
		&i.Quantity,
		&i.OrderSide,
		&i.OrderMode,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, ticker_id, price, quantity, order_side, order_mode, order_status, created_at, updated_at FROM orders
WHERE ID = $1 and user_id = $2 LIMIT 1
`

type GetOrderParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TickerID,
		&i.Price,
		&i.Quantity,
		&i.OrderSide,
		&i.OrderMode,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, ticker_id, price, quantity, order_side, order_mode, order_status, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListOrders(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TickerID,
			&i.Price,
			&i.Quantity,
			&i.OrderSide,
			&i.OrderMode,
			&i.OrderStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET order_status = $2, updated_at = now()
WHERE ID = $1
`

type UpdateOrderParams struct {
	ID          int64       `json:"id"`
	OrderStatus OrderStatus `json:"order_status"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder, arg.ID, arg.OrderStatus)
	return err
}
