// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (buyer_id, seller_id, price, quantity, side, type, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, buyer_id, seller_id, price, quantity, side, type, status, created_at, updated_at
`

type CreateOrderParams struct {
	BuyerID  uuid.UUID       `json:"buyer_id"`
	SellerID uuid.UUID       `json:"seller_id"`
	Price    decimal.Decimal `json:"price"`
	Quantity decimal.Decimal `json:"quantity"`
	Side     OrderSide       `json:"side"`
	Type     OrderType       `json:"type"`
	Status   OrderStatus     `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.BuyerID,
		arg.SellerID,
		arg.Price,
		arg.Quantity,
		arg.Side,
		arg.Type,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, buyer_id, seller_id, price, quantity, side, type, status, created_at, updated_at FROM orders
WHERE ID = $1 and buyer_id = $2 or seller_id = $2
LIMIT 1
`

type GetOrderParams struct {
	ID      int32     `json:"id"`
	BuyerID uuid.UUID `json:"buyer_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.BuyerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.SellerID,
		&i.Price,
		&i.Quantity,
		&i.Side,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, buyer_id, seller_id, price, quantity, side, type, status, created_at, updated_at FROM orders
WHERE buyer_id = $1 or seller_id = $1
`

func (q *Queries) ListOrders(ctx context.Context, buyerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.Price,
			&i.Quantity,
			&i.Side,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
