// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticker.sql

package repositories

import (
	"context"
)

const createTicker = `-- name: CreateTicker :one
INSERT INTO tickers (
    symbol, name
) VALUES (
  $1, $2
)
RETURNING id, symbol, name, last, ask, bid
`

type CreateTickerParams struct {
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

func (q *Queries) CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error) {
	row := q.db.QueryRow(ctx, createTicker, arg.Symbol, arg.Name)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Last,
		&i.Ask,
		&i.Bid,
	)
	return i, err
}

const deleteTicker = `-- name: DeleteTicker :exec
DELETE FROM tickers
WHERE ID = $1
`

func (q *Queries) DeleteTicker(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTicker, id)
	return err
}

const getTicker = `-- name: GetTicker :one
SELECT id, symbol, name, last, ask, bid FROM tickers
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetTicker(ctx context.Context, id int32) (Ticker, error) {
	row := q.db.QueryRow(ctx, getTicker, id)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Last,
		&i.Ask,
		&i.Bid,
	)
	return i, err
}

const listTickers = `-- name: ListTickers :many
SELECT id, symbol, name, last, ask, bid FROM tickers
ORDER BY name
`

func (q *Queries) ListTickers(ctx context.Context) ([]Ticker, error) {
	rows, err := q.db.Query(ctx, listTickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticker
	for rows.Next() {
		var i Ticker
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Last,
			&i.Ask,
			&i.Bid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
