// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticker.sql

package repositories

import (
	"context"
)

const createTicker = `-- name: CreateTicker :one
INSERT INTO tickers (
    symbol, base, quote, status
) VALUES ($1, $2, $3, $4)
RETURNING id, symbol, base, quote, status
`

type CreateTickerParams struct {
	Symbol string `json:"symbol"`
	Base   string `json:"base"`
	Quote  string `json:"quote"`
	Status Status `json:"status"`
}

func (q *Queries) CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error) {
	row := q.db.QueryRow(ctx, createTicker,
		arg.Symbol,
		arg.Base,
		arg.Quote,
		arg.Status,
	)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Base,
		&i.Quote,
		&i.Status,
	)
	return i, err
}

const deleteTicker = `-- name: DeleteTicker :exec
DELETE FROM tickers
WHERE ID = $1
`

func (q *Queries) DeleteTicker(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTicker, id)
	return err
}

const getTicker = `-- name: GetTicker :one
SELECT id, symbol, base, quote, status FROM tickers
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetTicker(ctx context.Context, id int32) (Ticker, error) {
	row := q.db.QueryRow(ctx, getTicker, id)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Base,
		&i.Quote,
		&i.Status,
	)
	return i, err
}

const listTickers = `-- name: ListTickers :many
SELECT id, symbol, base, quote, status FROM tickers
ORDER BY symbol
`

func (q *Queries) ListTickers(ctx context.Context) ([]Ticker, error) {
	rows, err := q.db.Query(ctx, listTickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticker
	for rows.Next() {
		var i Ticker
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Base,
			&i.Quote,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
