// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email_address, wallet_address, password, api_key, user_role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, first_name, last_name, email_address, wallet_address, password, api_key, user_role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FirstName     string   `json:"first_name"`
	LastName      string   `json:"last_name"`
	EmailAddress  string   `json:"email_address"`
	WalletAddress string   `json:"wallet_address"`
	Password      string   `json:"password"`
	ApiKey        *string  `json:"api_key"`
	UserRole      UserRole `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.WalletAddress,
		arg.Password,
		arg.ApiKey,
		arg.UserRole,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.WalletAddress,
		&i.Password,
		&i.ApiKey,
		&i.UserRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE ID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByApiKey = `-- name: FindUserByApiKey :one
SELECT id, first_name, last_name, email_address, wallet_address, password, api_key, user_role, created_at, updated_at, deleted_at FROM users
WHERE api_key = $1 LIMIT 1
`

func (q *Queries) FindUserByApiKey(ctx context.Context, apiKey *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.WalletAddress,
		&i.Password,
		&i.ApiKey,
		&i.UserRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, first_name, last_name, email_address, wallet_address, password, api_key, user_role, created_at, updated_at, deleted_at FROM users
WHERE email_address = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, emailAddress string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, emailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.WalletAddress,
		&i.Password,
		&i.ApiKey,
		&i.UserRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email_address, wallet_address, password, api_key, user_role, created_at, updated_at, deleted_at FROM users
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailAddress,
		&i.WalletAddress,
		&i.Password,
		&i.ApiKey,
		&i.UserRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email_address, wallet_address, password, api_key, user_role, created_at, updated_at, deleted_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailAddress,
			&i.WalletAddress,
			&i.Password,
			&i.ApiKey,
			&i.UserRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
