set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

run:
    @echo "Starting Portman Core"
    zig build run

test:
    @echo "Running tests"
    zig build test

fuzz amount="1K":
    @echo "Running fuzz test"
    zig build test --fuzz={{ amount }}
