set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

build:
    zig build

run:
    zig build run

test:
    zig build test

fuzz amount="1K":
    zig build test --fuzz={{ amount }}
