set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

build:
    forge build 

test:
    forge test -vvv

deploy script:
    forge script script/{{script}}.s.sol --rpc-url $ETHEREUM_RPC --account $ACCOUNT --password "$PASSWORD" --broadcast
