set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

start:
    @cargo run

build:
    @cargo build

test:
    @cargo test

generate:
    @forge bind --module --select PortmanAccount --select PortmanManager --root ../base --bindings-path ./src/contracts --overwrite
