set dotenv-load := true

default:
    @echo "No default task specified. Please choose a task to run."

start:
    air

build:
    go build -o ./tmp/main .

test:
    go test -v

generate:
    @mkdir -p contracts
    @abigen --v2 --abi ../base/tmp/PortmanDispenser.abi --bin ../base/tmp/PortmanDispenser.bin --pkg contracts --type Dispenser --out contracts/dispenser.go
