name: Issues

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v6
      - uses: alstr/todo-to-issue-action@v5
        with:
          AUTO_ASSIGN: "true"
          IDENTIFIERS: |
            [
              {"name": "FIX", "labels": ["bug"]},
              {"name": "FEAT", "labels": ["feature"]},
              {"name": "TEST", "labels": ["testing"]},
              {"name": "WARN", "labels": ["warning"]},
              {"name": "PERF", "labels": ["performance"]},
              {"name": "TODO", "labels": ["improvement"]},
              {"name": "DOCS", "labels": ["documentation"]},
            ]
