name: Releases

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: read
  issues: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yaml

  generate_issues_from_todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: alstr/todo-to-issue-action@v5
        with:
          AUTO_ASSIGN: "true"
          IDENTIFIERS: |
            [
              {"name": "BUG", "labels": ["bug"]},
              {"name": "TEST", "labels": ["testing"]},
              {"name": "WARN", "labels": ["warning"]},
              {"name": "TODO", "labels": ["enhancement"]},
              {"name": "PERF", "labels": ["performance"]},
              {"name": "DOCS", "labels": ["documentation"]}
            ]
